name: react-weather-app
#namespace: default
general:
  image: wededo4644/weather-app
  version: 89
  environment:
    ENVIRONMENT: production

scaling:
  replicas: 3

networking:
  expose: true
  port: 3000
